# Generated by Django 3.2.3 on 2021-07-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='wrong_op',
            field=models.TextField(verbose_name='Opção Incorreta'),
        ),
    ]
