# Generated by Django 3.2.3 on 2021-07-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0003_auto_20210730_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='order',
        ),
        migrations.AddField(
            model_name='quest',
            name='level',
            field=models.CharField(choices=[('F', 'Fácil'), ('N', 'Normal'), ('D', 'Difícil')], default='F', max_length=1, verbose_name='Nível de Dificuldade:'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.TextField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='correct_op',
            field=models.TextField(max_length=100, verbose_name='Opção Correta'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='wrong_op',
            field=models.TextField(max_length=100, verbose_name='Opção Incorreta'),
        ),
    ]
