# Generated by Django 3.2.3 on 2021-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0004_auto_20210730_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ('-created', 'name'), 'verbose_name': 'Vídeo', 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AddField(
            model_name='quest',
            name='name',
            field=models.CharField(default='Movimento do Vídeo', max_length=100, verbose_name='Título do Vídeo'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='correct_op',
            field=models.CharField(max_length=100, verbose_name='Opção Correta'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='timer',
            field=models.IntegerField(default=4, verbose_name='Segundos'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='videofile',
            field=models.FileField(upload_to='quests/%Y/%m/%d', verbose_name='Arquivo txt do vídeo'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='wrong_op',
            field=models.CharField(max_length=100, verbose_name='Opção Incorreta'),
        ),
    ]
