# Generated by Django 4.0.2 on 2022-02-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0005_auto_20210730_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('-created', 'name'), 'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
    ]
