# Generated by Django 4.0.2 on 2022-03-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0010_remove_quest_level_alter_experiment_quests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='speed',
            field=models.CharField(choices=[('F', 'Fast'), ('N', 'Normal'), ('S', 'Slow')], default='F', max_length=1, verbose_name='Velocidade'),
        ),
    ]
