# Generated by Django 4.0.2 on 2022-03-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0011_alter_quest_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='speed',
            field=models.CharField(choices=[('F', 'Rápido'), ('N', 'Normal'), ('S', 'Lento')], default='N', max_length=1, verbose_name='Velocidade'),
        ),
    ]
