# Generated by Django 4.0.2 on 2022-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0013_alter_quest_correct_op_alter_quest_wrong_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='wrong_op',
            field=models.CharField(blank=True, choices=[('1', 'Verde'), ('2', 'Vermelho')], max_length=1, null=True, verbose_name='Incorreta'),
        ),
    ]
